steps:
  # # Build the container image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/slides-generator', '.']
  
  # # Push the container image to Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/slides-generator']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'slides-generator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/slides-generator'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '100'

images:
  - 'gcr.io/$PROJECT_ID/slides-generator'